"""
PDF Generation Service - Converts markdown reports to PDF.

This service takes the final SEO analysis report in markdown format
and converts it to a professionally formatted PDF document.
"""

import os
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

from markdown_pdf import MarkdownPdf, Section

logger = logging.getLogger(__name__)

# Output directory for PDF files
OUTPUT_DIR = Path(__file__).parent / "outputs"


class PDFService:
    """
    Service for converting markdown reports to PDF documents.
    
    Uses the markdown-pdf library to generate professional PDF reports
    from the SEO analysis markdown output.
    """
    
    def __init__(self, output_dir: Optional[Path] = None):
        """
        Initialize the PDF service.
        
        Args:
            output_dir: Directory to save PDF files. Defaults to 'outputs' folder.
        """
        self.output_dir = output_dir or OUTPUT_DIR
        self._ensure_output_dir()
        logger.info(f"PDF Service initialized. Output directory: {self.output_dir}")
    
    def _ensure_output_dir(self):
        """Create the output directory if it doesn't exist."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        logger.debug(f"Output directory ensured: {self.output_dir}")
    
    def _sanitize_filename(self, url: str) -> str:
        """
        Create a safe filename from the URL.
        
        Args:
            url: The website URL
            
        Returns:
            A sanitized filename string
        """
        # Parse the URL to get the domain
        parsed = urlparse(url)
        domain = parsed.netloc or parsed.path
        
        # Remove www. prefix if present
        domain = re.sub(r'^www\.', '', domain)
        
        # Replace invalid filename characters
        safe_name = re.sub(r'[^\w\-.]', '_', domain)
        
        return safe_name
    
    def _add_header_to_markdown(self, markdown_content: str, url: str, request_id: str, score: int) -> str:
        """
        Add a professional header to the markdown content.
        
        Args:
            markdown_content: The original markdown content
            url: The analyzed website URL
            request_id: The unique request identifier
            score: The overall SEO score
            
        Returns:
            Enhanced markdown with header
        """
        header = f"""---

# 🔍 SEO Analysis Report

**Generated by:** SEO Analyzer - Google ADK Multi-Agent System  
**Report Date:** {datetime.now().strftime('%B %d, %Y at %H:%M')}  
**Website:** {url}  
**Request ID:** {request_id}  
**Overall Score:** {score}/100  

---

"""
        # Clean up the markdown content - remove any leading ```markdown and trailing ```
        content = markdown_content.strip()
        if content.startswith('```markdown'):
            content = content[11:]
        if content.startswith('```'):
            content = content[3:]
        if content.endswith('```'):
            content = content[:-3]
        
        return header + content.strip()
    
    def generate_pdf(
        self, 
        markdown_content: str, 
        url: str, 
        request_id: str,
        score: int = 0
    ) -> Optional[str]:
        """
        Generate a PDF from markdown content.
        
        Args:
            markdown_content: The markdown content to convert
            url: The analyzed website URL
            request_id: Unique request identifier
            score: Overall SEO score
            
        Returns:
            Path to the generated PDF file, or None if failed
        """
        try:
            # Generate filename
            safe_domain = self._sanitize_filename(url)
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"seo_report_{safe_domain}_{request_id}_{timestamp}.pdf"
            output_path = self.output_dir / filename
            
            logger.info(f"Generating PDF report: {filename}")
            
            # Enhance the markdown with header
            enhanced_markdown = self._add_header_to_markdown(
                markdown_content, url, request_id, score
            )
            
            # Create PDF using markdown-pdf
            pdf = MarkdownPdf(toc_level=2)
            pdf.add_section(Section(enhanced_markdown))
            pdf.meta["title"] = f"SEO Report - {safe_domain}"
            pdf.meta["author"] = "SEO Analyzer - Google ADK"
            pdf.meta["subject"] = f"SEO Analysis for {url}"
            pdf.meta["keywords"] = "SEO, analysis, website, optimization"
            
            # Save the PDF
            pdf.save(str(output_path))
            
            logger.info(f"PDF generated successfully: {output_path}")
            return str(output_path)
            
        except Exception as e:
            logger.error(f"Failed to generate PDF: {e}")
            return None
    
    def get_output_path(self) -> str:
        """Get the output directory path."""
        return str(self.output_dir)


# Global instance for easy access
_pdf_service: Optional[PDFService] = None


def get_pdf_service() -> PDFService:
    """Get or create the global PDF service instance."""
    global _pdf_service
    if _pdf_service is None:
        _pdf_service = PDFService()
    return _pdf_service


def generate_report_pdf(
    markdown_content: str,
    url: str,
    request_id: str,
    score: int = 0
) -> Optional[str]:
    """
    Convenience function to generate a PDF report.
    
    Args:
        markdown_content: The markdown content to convert
        url: The analyzed website URL
        request_id: Unique request identifier
        score: Overall SEO score
        
    Returns:
        Path to the generated PDF file, or None if failed
    """
    service = get_pdf_service()
    return service.generate_pdf(markdown_content, url, request_id, score)


if __name__ == "__main__":
    # Test the PDF service
    test_markdown = """
# Test SEO Report

## Executive Summary

This is a test report to verify PDF generation.

## Issues Found

- Issue 1: Test issue
- Issue 2: Another test issue

## Recommendations

1. First recommendation
2. Second recommendation
"""
    
    pdf_path = generate_report_pdf(
        markdown_content=test_markdown,
        url="https://example.com",
        request_id="test123",
        score=75
    )
    
    if pdf_path:
        print(f"✅ PDF generated: {pdf_path}")
    else:
        print("❌ Failed to generate PDF")
