import { motion } from 'framer-motion';
import { 
  Download, 
  RefreshCw, 
  CheckCircle2, 
  Loader2,
  FileText,
  Sparkles
} from 'lucide-react';
import { UserDetails } from '../types';

interface ResultsScreenProps {
  userDetails: UserDetails;
  onNewAnalysis: () => void;
  onDownloadPdf: () => void;
  isDownloading: boolean;
}

export function ResultsScreen({ 
  userDetails, 
  onNewAnalysis, 
  onDownloadPdf,
  isDownloading 
}: ResultsScreenProps) {
  const websiteName = userDetails.websiteUrl
    .replace(/^https?:\/\//, '')
    .replace(/\/$/, '');

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-12">
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full max-w-lg text-center"
      >
        {/* Success Icon */}
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ type: 'spring', delay: 0.2 }}
          className="mb-8"
        >
          <div className="w-24 h-24 mx-auto rounded-full bg-gradient-to-br from-green-500 to-emerald-600 flex items-center justify-center shadow-lg shadow-green-500/30">
            <CheckCircle2 className="w-12 h-12 text-white" />
          </div>
        </motion.div>

        {/* Success Message */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <h1 className="text-3xl font-bold text-white mb-3">
            Analysis Complete!
          </h1>
          <p className="text-gray-400 mb-2">
            Your SEO report for <span className="text-primary-400 font-medium">{websiteName}</span> is ready.
          </p>
          <p className="text-gray-500 text-sm mb-8">
            The comprehensive report has been generated by our AI agents.
          </p>
        </motion.div>

        {/* PDF Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="glass rounded-2xl p-8 mb-8 gradient-border"
        >
          <div className="flex items-center justify-center gap-4 mb-6">
            <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
              <FileText className="w-8 h-8 text-white" />
            </div>
            <div className="text-left">
              <h3 className="text-lg font-semibold text-white">SEO Analysis Report</h3>
              <p className="text-sm text-gray-400">PDF Document • Ready to download</p>
            </div>
          </div>

          {/* Download Button */}
          <motion.button
            onClick={onDownloadPdf}
            disabled={isDownloading}
            whileHover={{ scale: isDownloading ? 1 : 1.02 }}
            whileTap={{ scale: isDownloading ? 1 : 0.98 }}
            className="w-full flex items-center justify-center gap-3 px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-semibold text-lg shadow-lg hover:shadow-blue-500/25 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isDownloading ? (
              <>
                <Loader2 className="w-6 h-6 animate-spin" />
                Preparing Download...
              </>
            ) : (
              <>
                <Download className="w-6 h-6" />
                Download PDF Report
              </>
            )}
          </motion.button>
        </motion.div>

        {/* Analyze Another Button */}
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          onClick={onNewAnalysis}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          className="flex items-center justify-center gap-2 mx-auto px-6 py-3 text-gray-400 hover:text-white transition-colors"
        >
          <RefreshCw className="w-5 h-5" />
          Analyze Another Website
        </motion.button>

        {/* Footer Note */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="mt-12 flex items-center justify-center gap-2 text-sm text-gray-500"
        >
          <Sparkles className="w-4 h-4" />
          <span>Powered by Google ADK & Gemini 2.0 Flash</span>
        </motion.div>
      </motion.div>
    </div>
  );
}
